name: ifg_mobile_estudante
description: Aplicativo do Intituto federal de góias desenvolvido pelo núcleo NUMBERS para os estudantes de toda a instituição.
publish_to: "none"
version: 1.0.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       


environment:
  sdk: ">=3.1.0 <4.0.0"



dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

